version: 2.1
jobs:
  build-test:
    docker:
      - image: circleci/python:3.7.2-stretch

    working_directory: ~/
    steps:
      - run:
          name: Clone repo and install requirements
          command: |
            set -x
            git clone -b $CIRCLE_BRANCH https://github.com/sifnoc/tokamak-web-service-poc
            cd tokamak-web-service-poc
            virtualenv venv && source venv/bin/activate
            sudo -H pip install -r requirements.txt
            sudo -H pip install scp

      - run:
          name: Create key and config file
          command: |
            cd tokamak-web-service-poc
            echo ${AWS_TWS_DEV} > tws_dev.pem
            echo "[AWS]" >> config.ini
            echo "AWS_ACCESS_KEY = ${AWS_ACCESS_KEY_ID}" >> config.ini
            echo "AWS_SECRET_KEY = ${AWS_SECRET_ACCESS_KEY}" >> config.ini
            echo "[INSTANCE]" >> config.ini
            echo "BASIC_IMAGE_ID = ${BASIC_IMAGE_ID}" >> config.ini
            echo "INSTANCE_TYPE = ${INSTANCE_TYPE}" >> config.ini
            echo "SECURITY_GROUP_ID = ${SECURITY_GROUP_ID}" >> config.ini
            echo "KEY_NAME = ${KEY_NAME}" >> config.ini
            echo "REGION_NAME = ${REGION_NAME}" >> config.ini
            echo "[SSH]" >> config.ini
            echo "SSH_USERNAME = ${SSH_USERNAME}" >> config.ini
            echo "SSH_PEMFILE = ${SSH_PEMFILE}" >> config.ini
            echo "[SERVER]" >> config.ini
            echo "DEBUG = True" >> config.ini
            echo "SECRET_KEY = ${SECRET_KEY}" >> config.ini
            echo "USERNAME = ${USERNAME}" >> config.ini
            echo "PASSWORD = ${PASSWORD}" >> config.ini
            echo "[DATABASE]" >> config.ini
            echo "DATABASE = ${DATABASE}" >> config.ini

      - run:
          name: Run TWS server for test
          background: true
          command: |
            sudo python app.py

      - run:
          name: Check running TWS server
          command: |
            curl --retry 10 --retry-delay 3 --retry-connrefused  http://127.0.0.1:8000

  deploy:
    docker:
      - image: circleci/aws-code-deploy@1.0.1
    steps:
      - run:
          name: deploy TWS dev instance
          command: |
            aws deploy create-deployment \
                    --application-name TWS-dev \
                    --deployment-group-name TWS \
                    --github-location repository=sifnoc/tokamak-web-service-poc,commitId=$CIRCLE_SHA1

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-test
      - deploy:
          requires:
            - build-test

