version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7.2-stretch

    working_directory: ~/
    steps:
      - run:
          name: Clone repo and install requirements
          command: |
            set -x
            git clone https://github.com/Onther-Tech/tokamak-web-service-poc
            cd tokamak-web-service-poc
            virtualenv venv && source venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: Create key and config file
          command: |
            cd tokamak-web-service-poc
            echo ${AWS_TWS_DEV} > tws_dev.pem
            echo "[AWS]" >> config.ini
            echo "AWS_ACCESS_KEY = $(AWS_ACCESS_KEY)" >> config.ini
            echo "AWS_SECRET_KEY = ${AWS_SECRET_KEY}" >> config.ini
            echo "[INSTANCE]" >> config.ini
            echo "REGION_NAME = $AWS_REGION" >> config.ini

      - run:
          name: Run TWS server for test
          background: true
          command: |
            cd tokamak-web-service-poc
            source venv/bin/activate
            python app.py

      - run:
          name: Check Curl
          command: |
            curl --retry 10 --retry-delay 3 --retry-connrefused  http://127.0.0.1:8080

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
